name: newsletter-automation-test
on:
  push:
    branches: "**"
jobs:
  ci-tests:
    runs-on: ubuntu-latest
    environment: CI testing
    env: 
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          set -ex
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install selenium-tools
      - uses: nanasess/setup-chromedriver@v2
      - run: chromedriver --url-base=/wd/hub &
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Run Tests
        run: |
          cd tests/integration
          npm install -g --save-dev @percy/cli
          percy exec -- python -m pytest  tests/test_newsletter_automation.py
